// flow-typed signature: 873b2d9412cbdcf43bb24cdc5b1fb86b
// flow-typed version: <<STUB>>/html-webpack-template_v^6.2.0/flow_v0.100.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html-webpack-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html-webpack-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html-webpack-template/examples' {
  declare module.exports: any;
}

declare module 'html-webpack-template/examples/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html-webpack-template/examples/index' {
  declare module.exports: $Exports<'html-webpack-template/examples'>;
}
declare module 'html-webpack-template/examples/index.js' {
  declare module.exports: $Exports<'html-webpack-template/examples'>;
}
declare module 'html-webpack-template/examples/webpack.config.js' {
  declare module.exports: $Exports<'html-webpack-template/examples/webpack.config'>;
}
declare module 'html-webpack-template/index' {
  declare module.exports: $Exports<'html-webpack-template'>;
}
declare module 'html-webpack-template/index.js' {
  declare module.exports: $Exports<'html-webpack-template'>;
}
